"""add chatbot color theme

Revision ID: 19b72d831a85
Revises: 64a70a7aab8b
Create Date: 2024-06-03 04:42:56.740743

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '19b72d831a85'
down_revision = '64a70a7aab8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_color_theme', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chat_color_theme_inverted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('chat_color_theme_inverted')
        batch_op.drop_column('chat_color_theme')

    # ### end Alembic commands ###
